<OnboardingScreenView>
    md_bg_color: app.theme_cls.backgroundColor
    MDButton:
        pos_hint: {'center_x': .9, 'top': .98}
        style: 'text'
        MDButtonText:
            text: 'Skip'


    Image:
        source: 'assets/images/Group 8.png'
        size_hint: .8, .8
        pos_hint: {'center_x': .5, 'center_y': .5}


    MDButton:
        pos_hint: {'center_x': .5, 'center_y': .15}
        MDButtonIcon:
            icon: 'assets/images/Group6.png'
            size_hint: .2, .2
